<?php

namespace Wcs\WildResaBundle\Entity;

/**
 * EventsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventsRepository extends \Doctrine\ORM\EntityRepository
{
    public function findbyperiod($start, $end){

    }
}
